# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 258)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.commentLabel = QtWidgets.QLabel(self.centralwidget)
        self.commentLabel.setObjectName("commentLabel")
        self.gridLayout.addWidget(self.commentLabel, 1, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.commentLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.gridLayout.addWidget(self.commentLineEdit, 1, 1, 1, 1)
        self.commandLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.commandLineEdit.setObjectName("commandLineEdit")
        self.gridLayout.addWidget(self.commandLineEdit, 3, 1, 1, 1)
        self.iconLabel = QtWidgets.QLabel(self.centralwidget)
        self.iconLabel.setObjectName("iconLabel")
        self.gridLayout.addWidget(self.iconLabel, 2, 0, 1, 1)
        self.commandLabel = QtWidgets.QLabel(self.centralwidget)
        self.commandLabel.setObjectName("commandLabel")
        self.gridLayout.addWidget(self.commandLabel, 3, 0, 1, 1)
        self.iconHorizontalLayout = QtWidgets.QHBoxLayout()
        self.iconHorizontalLayout.setSpacing(10)
        self.iconHorizontalLayout.setObjectName("iconHorizontalLayout")
        self.iconLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLineEdit.sizePolicy().hasHeightForWidth())
        self.iconLineEdit.setSizePolicy(sizePolicy)
        self.iconLineEdit.setObjectName("iconLineEdit")
        self.iconHorizontalLayout.addWidget(self.iconLineEdit)
        self.iconButton = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.iconButton.setIcon(icon)
        self.iconButton.setObjectName("iconButton")
        self.iconHorizontalLayout.addWidget(self.iconButton)
        self.gridLayout.addLayout(self.iconHorizontalLayout, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.submitHorizontalLayout = QtWidgets.QHBoxLayout()
        self.submitHorizontalLayout.setObjectName("submitHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submitHorizontalLayout.addItem(spacerItem)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        self.submitButton.setObjectName("submitButton")
        self.submitHorizontalLayout.addWidget(self.submitButton)
        self.verticalLayout.addLayout(self.submitHorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Desktop Entry Creator"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.commentLabel.setText(_translate("MainWindow", "Comment"))
        self.iconLabel.setText(_translate("MainWindow", "Icon"))
        self.commandLabel.setText(_translate("MainWindow", "Command"))
        self.iconButton.setText(_translate("MainWindow", "..."))
        self.submitButton.setText(_translate("MainWindow", "Create"))
